name: Terraform CI/CD

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Apply (Dev)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # 3. Verify Terraform installation (debug-safe)
      - name: Verify Terraform
        run: terraform version

      # 4. Configure AWS credentials using OIDC
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::273605040540:role/github-actions-terraform-role
          aws-region: ap-south-1

      # 5. Terraform Init (uses S3 + DynamoDB backend)
      - name: Terraform Init
        run: terraform init -input=false

      # 6. Terraform Plan
      - name: Terraform Plan
        run: terraform plan -input=false -var-file=../envs/dev.tfvars

      # 7. Terraform Apply (only on main)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -input=false -auto-approve
